// TODO: Add more words

export const words = [
  { word: 'Ottoman Empire', category: 'Empire', hint: 'Historical Empire' },
  { word: 'Roman Empire', category: 'Empire', hint: 'Late Iron Age Empire' },
  { word: 'Mongol Empire', category: 'Empire', hint: 'Vast Asian Empire' },
  { word: 'British Empire', category: 'Empire', hint: 'Largest Colonial Power' },
  { word: 'Macedonian Empire', category: 'Empire', hint: 'Macedonian Era' },
  { word: 'Inca Empire', category: 'Empire', hint: 'South American Civilization' },
  { word: 'Achaemenid Empire', category: 'Empire', hint: 'Persian Empire' },
  { word: 'Aztec Empire', category: 'Empire', hint: 'Central American Civilization' },
  { word: 'Mughal Empire', category: 'Empire', hint: 'Early Modern India' },
  { word: 'Han Empire', category: 'Empire', hint: 'Chinese Dynasty' },
  { word: 'Rashidun Caliphate', category: 'Empire', hint: 'Historical Muslim Empire' },

  { word: 'Rolls Royce Phantom', category: 'Car', hint: 'Luxury Car' },
  { word: 'Toyota Supra', category: 'Car', hint: 'Sports Car' },
  { word: 'Lamborghini', category: 'Car', hint: 'Sports Car' },
  { word: 'Buggati', category: 'Car', hint: 'Sports Car' },
  { word: 'Mercedes', category: 'Car', hint: 'Luxury Car' },
  { word: 'Lexus', category: 'Car', hint: 'Luxury Car' },
  { word: 'Porsche', category: 'Car', hint: 'Sports Car' },

  { word: 'Prophet Suleiman', category: 'Ruler', hint: 'Third King of Israel' },
  { word: 'Prophet ', category: 'Ruler', hint: 'Third King of Israel' },
  { word: 'Catherine the Great', category: 'Ruler', hint: 'Russian Empress' },
  { word: 'Sultan Suleiman', category: 'Ruler', hint: 'Ottoman Ruler' },
  { word: 'Sultan Mehmet Fatih', category: 'Ruler', hint: 'Ottoman Ruler' },
  { word: 'Yavuz Sultan Selim', category: 'Ruler', hint: 'Ottoman Ruler' },
  { word: 'Sultan Abdul Hamid', category: 'Ruler', hint: 'Ottoman Ruler' },
  { word: 'Caliph Umar', category: 'Ruler', hint: 'Caliph' },
  { word: 'Tariq Bin Zyad', category: 'Ruler', hint: 'Conquerer of Spain' },
  { word: 'Alexander The Great', category: 'Ruler', hint: 'Conquered Half of World' },
  { word: 'Winston Churchill', category: 'Ruler', hint: 'World War II' },

  { word: 'Al Khwarzmi', category: 'Scientist', hint: 'Persian Muslim' },
  { word: 'Albert Einstein', category: 'Scientist', hint: 'German' },
  { word: 'Oppenheimer', category: 'Scientist', hint: 'Destroyer of Worlds' },
  { word: 'Stephen Hawking', category: 'Scientist', hint: 'Black Hole Radiations' },
  { word: 'Nikola Tesla', category: 'Scientist', hint: 'Alternating Current' },
  { word: 'Edwin Hubble', category: 'Scientist', hint: 'Hubble Space Telescope' },
  { word: 'Alexander Graham Bell', category: 'Scientist', hint: 'Telephone' },
  { word: 'Isaac Newton', category: 'Scientist', hint: 'Discovered Gravity' },
  { word: 'Michael Faraday', category: 'Scientist', hint: 'Electromagnetic Induction' },

  { word: 'Russia', category: 'Country', hint: 'Largest Country' },
  { word: 'United States', category: 'Country', hint: 'Biggest Economy' },
  { word: 'Saudi Arabia', category: 'Country', hint: 'Has No Lake' },
  { word: 'Vatican City', category: 'Country', hint: 'Smallest Country' },
  { word: 'India', category: 'Country', hint: 'Largest Population' },
  { word: 'South Africa', category: 'Country', hint: 'Cape of Good Hope' },
  { word: 'Albania', category: 'Country', hint: 'State Religion: Atheist' },
  { word: 'Kazakhstan', category: 'Country', hint: 'Largest Uranium Reserves' },
  { word: 'Turkey', category: 'Country', hint: 'Former Calipahte' },
  { word: 'Australia', category: 'Country', hint: 'As Big As Europe' },

  { word: 'Apple', category: 'Company', hint: 'Expensive Products' },
  { word: 'Samsung', category: 'Company', hint: 'Quality Mobile Phones' },
  { word: 'Nokia', category: 'Company', hint: 'Never Breaking Phones' },
  { word: 'Microsoft', category: 'Company', hint: 'All Over Computers' },
  { word: 'Google', category: 'Company', hint: 'All Over Internet' },
];

export const alphabets = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]